version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8001:8001"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=http://127.0.0.1:8001/auth/callback
    env_file:
      - .env
